# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               MrcSec
tagline:             'Just Another Security Blog'
description:         'A place to share ideas, tutorials & walkthroughs related to Information Security and Penetration Testing'
url:                 https://mrcopy.github.io
baseurl:             '/'
plugins:
  - jekyll-paginate
paginate:            5

# About/contact
author:
  name:              Lautaro Colombo
  url:               https://twitter.com/mrcopy_
  email:             lautaro@lautarocolombo.com

# Custom vars
version:             1.0.0
